name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "snzyjr" --password-stdin
        docker image build -t snzyjr/metris:samp .
        docker push snzyjr/metris:samp